import { build } from 'esbuild';
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
const entry = fileURLToPath(new URL('../src/pages.js', import.meta.url));
const output = new URL('../../frontend/_worker.js', import.meta.url);
const result = await build({
  entryPoints: [entry], bundle: true, format: 'esm', platform: 'browser',
  conditions: ['worker', 'browser'], target: 'es2022', write: false,
  banner: { js: '// Generated by worker/scripts/build-pages.mjs. Do not edit directly.\n// Contains no credentials. Cloudflare Pages deploys this alongside the frontend.' },
  absWorkingDir: fileURLToPath(new URL('../../', import.meta.url)),
});
const code = result.outputFiles[0].text;
if (process.argv.includes('--check')) {
  if (await readFile(output, 'utf8') !== code) {
    throw new Error('frontend/_worker.js is stale. Run npm --prefix worker run build:pages and commit the result.');
  }
  console.log('Pages backend bundle matches its source.');
} else {
  await writeFile(output, code);
  console.log('Built frontend/_worker.js for the existing no-build-step Pages deployment.');
}
