// Generated by worker/scripts/build-pages.mjs. Do not edit directly.
// Contains no credentials. Cloudflare Pages deploys this alongside the frontend.

// worker/src/teachassist-session.js
var TeachAssistError = class extends Error {
  constructor(code, message, { status = 502, retryable = false } = {}) {
    super(message);
    this.code = code;
    this.status = status;
    this.retryable = retryable;
  }
};
var failure = (code, message, retryable = false) => new TeachAssistError(code, message, { retryable });
var rejection = () => new TeachAssistError(
  "TA_LOGIN_REJECTED",
  "TeachAssist declined this sign-in. If these details work on the official site, please try again here.",
  { status: 401 }
);
function cookieLines(response) {
  const headers = response.headers;
  const lines = typeof headers.getSetCookie === "function" ? headers.getSetCookie() : [headers.get("set-cookie") || ""];
  return lines.flatMap((line) => line.split(/,(?=\s*[^\s;,=]+\s*=)/));
}
function mergeCookies(jar, response) {
  for (const raw of cookieLines(response)) {
    const [pair, ...attributes2] = raw.split(";");
    const at = pair.indexOf("=");
    if (at < 1) continue;
    const name = pair.slice(0, at).trim(), value = pair.slice(at + 1).trim();
    const maxAge = attributes2.find((a) => /^\s*max-age\s*=/i.test(a))?.split("=")[1];
    const expiryAttribute = attributes2.find((a) => /^\s*expires\s*=/i.test(a));
    const expires = expiryAttribute?.slice(expiryAttribute.indexOf("=") + 1);
    const cleared = !value || value.toLowerCase() === "deleted" || (maxAge !== void 0 ? Number(maxAge) <= 0 : expires && Date.parse(expires) <= Date.now());
    if (cleared) delete jar[name];
    else jar[name] = value;
  }
  return jar;
}
function extractCookies(response) {
  return mergeCookies(/* @__PURE__ */ Object.create(null), response);
}
function cookieHeader(jar) {
  return Object.entries(jar).map(([k, v]) => `${k}=${v}`).join("; ");
}
function decode(value) {
  return value.replace(/&amp;/gi, "&").replace(/&quot;/gi, '"').replace(/&#(?:0*39|x0*27);/gi, "'").replace(/&#(\d+);/g, (_, n) => Number(n) <= 1114111 ? String.fromCodePoint(Number(n)) : "");
}
function attributes(tag) {
  const values = /* @__PURE__ */ Object.create(null);
  for (const match of tag.matchAll(/\b([\w:-]+)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+))/g))
    values[match[1].toLowerCase()] = decode(match[2] ?? match[3] ?? match[4]);
  return values;
}
function hasPasswordField(html) {
  return [...html.matchAll(/<input\b[^>]*>/gi)].some(([tag]) => {
    const attr = attributes(tag);
    return attr.type?.toLowerCase() === "password";
  });
}
function assertLoggedIn(html) {
  if (hasPasswordField(html)) throw failure(
    "TA_SESSION_REJECTED",
    "TeachAssist returned to its login page before your marks loaded. Please try signing in again.",
    true
  );
  if (/cf-chl-|<title>\s*Just a moment/i.test(html)) throw failure(
    "TA_UPSTREAM_BLOCKED",
    "TeachAssist is asking this server for a browser verification. You can still use the official TeachAssist site."
  );
}
function createTeachAssistSession({ origin, loginUrl, courseListUrl, fields, userAgent }) {
  function safeUrl(value, base) {
    let url;
    try {
      url = new URL(value, base);
    } catch {
      throw failure("TA_REDIRECT_INVALID", "TeachAssist returned an unsupported sign-in redirect.");
    }
    if (url.origin !== origin || url.username || url.password)
      throw failure("TA_REDIRECT_INVALID", "TeachAssist returned an unsupported sign-in redirect.");
    url.hash = "";
    return url;
  }
  async function request(url, options, deadline = Date.now() + 12e3) {
    const remaining = deadline - Date.now();
    if (remaining <= 0) throw failure("TA_TIMEOUT", "TeachAssist took too long to respond. Please try again.");
    let response;
    try {
      response = await fetch(url, {
        ...options,
        redirect: "manual",
        signal: AbortSignal.timeout(Math.min(12e3, remaining)),
        headers: { "user-agent": userAgent, accept: "text/html,application/xhtml+xml", ...options.headers }
      });
    } catch {
      throw failure("TA_CONNECTION_FAILED", "The server could not connect to TeachAssist. Please try again shortly.", true);
    }
    if (response.status === 429) throw new TeachAssistError(
      "TA_RATE_LIMITED",
      "TeachAssist is limiting sign-in attempts. Please wait a few minutes before trying again.",
      { status: 503 }
    );
    if (response.status === 401 || response.status === 403) throw failure(
      "TA_UPSTREAM_BLOCKED",
      "TeachAssist refused the server connection. Your password has not been verified. Please use the official site for now."
    );
    if (response.status >= 400) throw failure(
      "TA_UPSTREAM_UNAVAILABLE",
      "TeachAssist is temporarily unavailable to this server. Please try again shortly.",
      response.status >= 500
    );
    return response;
  }
  function idFrom(url, jar, html = "") {
    const input = [...html.matchAll(/<input\b[^>]*>/gi)].map(([tag]) => attributes(tag)).find((a) => a.name === "student_id");
    const candidates = [url.searchParams.get("student_id"), jar.student_id, input?.value];
    for (const [tag] of html.matchAll(/<a\b[^>]*>/gi)) {
      const href = attributes(tag).href;
      if (!href) continue;
      try {
        const link = safeUrl(href, url);
        if (link.pathname.startsWith("/live/students/")) candidates.push(link.searchParams.get("student_id"));
      } catch {
      }
    }
    return candidates.find((value) => typeof value === "string" && /^\d+$/.test(value)) || null;
  }
  function isErrorRedirect(url) {
    return [...url.searchParams.keys()].some((key2) => key2.toLowerCase() === "error");
  }
  async function follow(response, url, jar, { deadline, afterLogin = false, method = "GET", body } = {}) {
    let studentId = null;
    for (let redirects = 0; ; redirects++) {
      mergeCookies(jar, response);
      studentId = idFrom(url, jar) || studentId;
      if (response.status < 300 || response.status >= 400) {
        const html = await response.text();
        return { url, html, studentId: idFrom(url, jar, html) || studentId };
      }
      if (redirects >= 5 || !response.headers.get("location"))
        throw failure("TA_REDIRECT_LIMIT", "TeachAssist did not finish its sign-in redirects. Please try again.");
      const next = safeUrl(response.headers.get("location"), url);
      if (afterLogin && isErrorRedirect(next)) throw rejection();
      if (response.status === 303 || (response.status === 301 || response.status === 302) && method === "POST") {
        method = "GET";
        body = void 0;
      }
      const referer = url.href;
      url = next;
      response = await request(url.href, { method, body, headers: {
        cookie: cookieHeader(jar),
        referer,
        ...method === "POST" ? { "content-type": "application/x-www-form-urlencoded", origin } : {}
      } }, deadline);
    }
  }
  function formFor(html, base) {
    const forms = [...html.matchAll(/<form\b[^>]*>[\s\S]*?<\/form\s*>/gi)].map((m) => m[0]);
    const form = forms.find(hasPasswordField);
    const hidden = /* @__PURE__ */ Object.create(null);
    let action = new URL(loginUrl);
    if (form) {
      action = safeUrl(attributes(form.slice(0, form.indexOf(">") + 1)).action || base.href, base);
      for (const [tag] of form.matchAll(/<input\b[^>]*>/gi)) {
        const input = attributes(tag);
        if (input.type?.toLowerCase() === "hidden" && input.name && ![fields.username, fields.password, "submit"].includes(input.name)) hidden[input.name] = input.value || "";
      }
    }
    return { action, hidden };
  }
  function formBody(env, creds, hidden = {}) {
    const body = new URLSearchParams({ ...fields.extra, ...hidden });
    body.set(fields.username, creds?.username ?? env.TA_USERNAME ?? "");
    body.set(fields.password, creds?.password ?? env.TA_PASSWORD ?? "");
    return body.toString();
  }
  async function loginResponse2(env, creds) {
    return request(loginUrl, { method: "POST", headers: {
      "content-type": "application/x-www-form-urlencoded",
      origin,
      referer: loginUrl
    }, body: formBody(env, creds) });
  }
  async function login2(env, creds) {
    const deadline = Date.now() + 3e4;
    async function complete(response, action, jar, body) {
      const landed = await follow(response, action, jar, { deadline, afterLogin: true, method: "POST", body });
      if (hasPasswordField(landed.html) && /(?:invalid|incorrect|wrong)\s+(?:student\s+(?:number|id)|username|password|credentials)|(?:username|password)\s+(?:is\s+)?(?:invalid|incorrect)/i.test(landed.html)) throw rejection();
      assertLoggedIn(landed.html);
      if (!Object.keys(jar).length) throw failure(
        "TA_SESSION_MISSING",
        "TeachAssist did not create a sign-in session. Please try again; your password has not been verified.",
        true
      );
      if (!landed.studentId) throw failure(
        "TA_STUDENT_ID_MISSING",
        "TeachAssist did not return your student record after sign-in. Please try again.",
        true
      );
      const session = { jar, cookie: cookieHeader(jar), studentId: landed.studentId };
      if (landed.url.pathname === new URL(courseListUrl).pathname && landed.url.searchParams.get("student_id") === landed.studentId)
        session.listHtml = landed.html;
      return session;
    }
    try {
      const jar = /* @__PURE__ */ Object.create(null);
      const body = formBody(env, creds);
      const response = await request(loginUrl, { method: "POST", body, headers: {
        "content-type": "application/x-www-form-urlencoded",
        origin,
        referer: loginUrl
      } }, deadline);
      return await complete(response, new URL(loginUrl), jar, body);
    } catch (err) {
      if (!(err instanceof TeachAssistError) || ["TA_REDIRECT_INVALID", "TA_RATE_LIMITED"].includes(err.code)) throw err;
    }
    for (let attempt = 1; ; attempt++) {
      try {
        const jar = /* @__PURE__ */ Object.create(null);
        const first = await request(loginUrl, { method: "GET", headers: {} }, deadline);
        const initial = await follow(first, new URL(loginUrl), jar, { deadline });
        const form = formFor(initial.html, initial.url);
        const body = formBody(env, creds, form.hidden);
        const submitted = await request(form.action.href, { method: "POST", body, headers: {
          "content-type": "application/x-www-form-urlencoded",
          origin,
          referer: initial.url.href,
          cookie: cookieHeader(jar)
        } }, deadline);
        return await complete(submitted, form.action, jar, body);
      } catch (err) {
        if (!(err instanceof TeachAssistError) || !err.retryable || attempt >= 2 || Date.now() + 300 >= deadline) throw err;
        await new Promise((resolve) => setTimeout(resolve, 300));
      }
    }
  }
  async function fetchWithSession2(targetUrl, session, referer) {
    const url = safeUrl(targetUrl, origin);
    const deadline = Date.now() + 12e3;
    const response = await request(url.href, { method: "GET", headers: { cookie: cookieHeader(session.jar), referer } }, deadline);
    const landed = await follow(response, url, session.jar, { deadline });
    session.cookie = cookieHeader(session.jar);
    if (landed.url.pathname.startsWith("/yrdsb/")) throw failure(
      "TA_SESSION_REJECTED",
      "TeachAssist redirected back to sign-in before your marks loaded. Please try again.",
      true
    );
    assertLoggedIn(landed.html);
    return landed.html;
  }
  return { login: login2, loginResponse: loginResponse2, fetchWithSession: fetchWithSession2, assertLoggedIn };
}

// worker/src/session.js
var encoder = new TextEncoder();
var hex = (bytes) => Array.from(new Uint8Array(bytes), (n) => n.toString(16).padStart(2, "0")).join("");
async function key(secret) {
  return crypto.subtle.importKey("raw", encoder.encode(secret), { name: "HMAC", hash: "SHA-256" }, false, ["sign", "verify"]);
}
async function issueSession(secret, now = Date.now()) {
  if (!secret) return "";
  const payload = `${Math.floor(now / 1e3) + 3600}.${crypto.randomUUID()}`;
  return `${payload}.${hex(await crypto.subtle.sign("HMAC", await key(secret), encoder.encode(payload)))}`;
}
async function verifySession(token, secret, now = Date.now()) {
  if (!secret || typeof token !== "string") return false;
  const parts = token.match(/^(\d+)\.([a-f0-9-]{36})\.([a-f0-9]{64})$/);
  if (!parts || +parts[1] <= Math.floor(now / 1e3)) return false;
  const signature = Uint8Array.from(parts[3].match(/../g), (h) => parseInt(h, 16));
  return crypto.subtle.verify("HMAC", await key(secret), signature, encoder.encode(`${parts[1]}.${parts[2]}`));
}

// frontend/js/grade-math.js
function percent(n, label) {
  if (typeof n !== "number" || !Number.isFinite(n) || n < 0 || n > 100)
    throw new Error(`${label} must be between 0 and 100.`);
}
function requiredGrade(current, target, remaining) {
  percent(current, "Current grade");
  percent(target, "Target");
  percent(remaining, "Remaining weight");
  if (remaining === 0)
    throw new Error("Remaining weight must be greater than zero.");
  return (target - current * (1 - remaining / 100)) / (remaining / 100);
}
function projectedGrade(current, score, remaining) {
  percent(current, "Current grade");
  percent(score, "Expected score");
  percent(remaining, "Remaining weight");
  return current * (1 - remaining / 100) + score * remaining / 100;
}
function weightedAverage(rows) {
  if (!Array.isArray(rows) || !rows.length)
    throw new Error("Add at least one score.");
  let sum = 0, total = 0;
  for (const r of rows) {
    percent(r.score, "Score");
    percent(r.weight, "Weight");
    sum += r.score * r.weight;
    total += r.weight;
  }
  if (!total) throw new Error("Total weight must be greater than zero.");
  return sum / total;
}
function calculatePlan(p) {
  if (!p || typeof p !== "object")
    throw new Error("Please provide the grades and weights.");
  const f = (n) => Number(n).toFixed(2);
  if (p.kind === "arithmetic") {
    const v = arithmetic(p.expression);
    return {
      value: v,
      text: `${p.expression} = ${Number(v.toPrecision(12))}
Calculated with standard operator precedence. % means divide by 100; decimal results are rounded to 12 significant digits.`
    };
  }
  if (p.kind === "required") {
    const v = requiredGrade(p.current, p.target, p.remaining);
    return {
      value: v,
      text: `You need ${f(v)}% on the remaining work.
(${p.target} \u2212 ${p.current} \xD7 ${f(1 - p.remaining / 100)}) \xF7 ${f(p.remaining / 100)} = ${f(v)}%
${v > 100 ? "This target is not reachable with a maximum score of 100%." : v < 0 ? "Your target is already secured under these weights, even with 0% on the remaining work." : "Assumes your current mark represents all completed work and the remaining weight is accurate."}`
    };
  }
  if (p.kind === "projected") {
    const v = projectedGrade(p.current, p.score, p.remaining);
    return {
      value: v,
      text: `Your projected final grade is ${f(v)}%.
${p.current} \xD7 ${f(1 - p.remaining / 100)} + ${p.score} \xD7 ${f(p.remaining / 100)} = ${f(v)}%
Assumes the supplied weights describe your final grade.`
    };
  }
  if (p.kind === "average") {
    const v = weightedAverage(p.rows);
    return {
      value: v,
      text: `Your weighted average is ${f(v)}%.
Sum of (score \xD7 weight) \xF7 total weight. Weights are normalized across the scores you supplied.`
    };
  }
  throw new Error(
    "Use a target-grade, projected-grade, or weighted-average question."
  );
}
function arithmetic(expression) {
  if (typeof expression !== "string" || expression.length > 500)
    throw new Error("Use an expression of up to 500 characters.");
  if (/[\d.]\s+[\d.]/.test(expression))
    throw new Error("Put an operator between numbers.");
  const source = expression.replace(/×/g, "*").replace(/÷/g, "/").replace(/−/g, "-").replace(/\s+/g, "");
  const tokens = source.match(/(?:\d+(?:\.\d*)?|\.\d+)|sqrt|[()+\-*/^%]/g) || [];
  if (tokens.join("") !== source || !tokens.length)
    throw new Error("Use numbers, +, \u2212, \xD7, \xF7, ^, %, sqrt(), and parentheses.");
  let at = 0, depth = 0;
  function atom() {
    if (++depth > 80) throw new Error("Expression is too deeply nested.");
    let n, t = tokens[at++];
    if (t === "(") {
      n = sum();
      if (tokens[at++] !== ")") throw new Error("Close each parenthesis.");
    } else if (t === "sqrt") {
      if (tokens[at++] !== "(") throw new Error("Use sqrt(number).");
      n = Math.sqrt(sum());
      if (tokens[at++] !== ")") throw new Error("Close each parenthesis.");
    } else if (t && /^\d|^\./.test(t)) {
      n = Number(t);
    } else throw new Error("A number is missing.");
    depth--;
    while (tokens[at] === "%") {
      at++;
      n /= 100;
    }
    return n;
  }
  function power() {
    const left = atom();
    if (tokens[at] === "^") {
      at++;
      return left ** unary();
    }
    return left;
  }
  function unary() {
    if (tokens[at] === "+") {
      at++;
      return unary();
    }
    if (tokens[at] === "-") {
      at++;
      return -unary();
    }
    return power();
  }
  function product() {
    let n = unary();
    while (tokens[at] === "*" || tokens[at] === "/") {
      const op = tokens[at++], r = unary();
      if (op === "/" && r === 0)
        throw new Error("Division by zero is undefined.");
      n = op === "*" ? n * r : n / r;
    }
    return n;
  }
  function sum() {
    let n = product();
    while (tokens[at] === "+" || tokens[at] === "-") {
      const op = tokens[at++], r = product();
      n = op === "+" ? n + r : n - r;
    }
    return n;
  }
  const value = sum();
  if (at !== tokens.length)
    throw new Error("Check the operators and parentheses.");
  if (!Number.isFinite(value))
    throw new Error("This expression has no finite real result.");
  return value;
}

// worker/src/assistant.js
async function interpretQuestion(request, env) {
  if (!env.AI)
    return {
      status: 503,
      body: {
        error: "AI is not connected yet. The quick calculator works now."
      }
    };
  const reader = request.body?.getReader();
  if (!reader) return { status: 400, body: { error: "Enter a question." } };
  let size = 0, chunks = [];
  for (; ; ) {
    const { done, value } = await reader.read();
    if (done) break;
    size += value.byteLength;
    if (size > 8192) {
      await reader.cancel();
      return { status: 413, body: { error: "Please shorten your question." } };
    }
    chunks.push(value);
  }
  let input;
  try {
    const bytes = new Uint8Array(size);
    let at = 0;
    for (const c of chunks) {
      bytes.set(c, at);
      at += c.length;
    }
    input = JSON.parse(new TextDecoder().decode(bytes));
  } catch {
    return { status: 400, body: { error: "Invalid question format." } };
  }
  if (typeof input?.question !== "string" || !input.question.trim() || input.question.length > 1500)
    return {
      status: 400,
      body: { error: "Enter a question of up to 1,500 characters." }
    };
  try {
    const result = await env.AI.run("@cf/meta/llama-3.1-8b-instruct", {
      messages: [
        {
          role: "system",
          content: `You extract math and grade calculation inputs. Return only one JSON object. Never calculate answers. Supported schemas: {"kind":"required","current":85,"target":90,"remaining":30}, {"kind":"projected","current":85,"score":90,"remaining":30}, {"kind":"average","rows":[{"score":85,"weight":70},{"score":90,"weight":30}]}. For arithmetic use {"kind":"arithmetic","expression":"(12 + 8) / 2"}. Supported arithmetic: numbers, + - * / ^ % sqrt() and parentheses only, no variables. Grade input numbers are percentages 0 to 100. Current means the average of completed work, remaining means percentage of the entire final grade still ungraded. Use only explicitly supplied numbers. Never assume an exam weight. For missing data, ambiguous questions, unsupported math, or unrelated questions return {"clarification":"a concise request for the missing inputs, asking the user to resubmit the complete question"}. Each request is independent; there is no conversation history.`
        },
        { role: "user", content: input.question }
      ],
      max_tokens: 400,
      temperature: 0,
      response_format: { type: "json_object" }
    });
    const plan = JSON.parse(result.response);
    if (typeof plan.clarification === "string")
      return {
        status: 200,
        body: { clarification: plan.clarification.slice(0, 700) }
      };
    calculatePlan(plan);
    return { status: 200, body: { plan } };
  } catch {
    return {
      status: 502,
      body: {
        error: "I could not interpret that reliably. Include your current grade, target, and remaining weight, or use the quick calculator."
      }
    };
  }
}

// worker/src/index.js
var DASHBOARD_ORIGIN = "https://teachassist.pages.dev";
var REQUIRE_API_KEY = true;
var API_KEY_HEADER = "x-api-key";
var TA_ORIGIN = "https://ta.yrdsb.ca";
var LOGIN_URL = `${TA_ORIGIN}/yrdsb/index.php`;
var COURSE_LIST_URL = `${TA_ORIGIN}/live/students/listReports.php`;
var REPORT_URL_BASE = `${TA_ORIGIN}/live/students/viewReport.php`;
var LOGIN_FIELDS = {
  username: "username",
  password: "password",
  extra: {
    subject_id: "0",
    submit: "Login"
  }
};
var SESSION_COOKIE_NAME = "session_token";
var FETCH_REPORTS = true;
var STRAND_COLOURS = {
  ffffaa: "Knowledge/Understanding",
  c0fea4: "Thinking",
  afafff: "Communication",
  ffd490: "Application",
  eeeeee: "Other",
  // the real report uses #eeeeee for "Other"
  dedede: "Other",
  // kept as an alternate
  cccccc: "Final"
  // "Final/Culminating"
};
var COURSE_CODE_RE = /\b([A-Z]{2,5}\d[A-Z0-9]{1,3}(?:-\d{1,2})?)\b/;
var BROWSER_UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36";
var DEBUG = true;
var { login, loginResponse, fetchWithSession, assertLoggedIn: assertLoggedIn2 } = createTeachAssistSession({
  origin: TA_ORIGIN,
  loginUrl: LOGIN_URL,
  courseListUrl: COURSE_LIST_URL,
  fields: LOGIN_FIELDS,
  userAgent: BROWSER_UA
});
var index_default = {
  /**
   * @param {Request} request
   * @param {{ TA_USERNAME?: string, TA_PASSWORD?: string, API_KEY?: string, MARKS?: KVNamespace }} env
   * @param {{ waitUntil?: (p: Promise<any>) => void }} [ctx]
   */
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    if (request.method === "OPTIONS") {
      return new Response(null, { status: 204, headers: corsHeaders() });
    }
    if (url.pathname === "/api/assistant") {
      if (request.method !== "POST") return json({ error: "Use POST." }, 405);
      const provided = request.headers.get(API_KEY_HEADER);
      if (!(env.API_KEY && provided && timingSafeEqual(provided, env.API_KEY)) && !await verifySession(request.headers.get("Authorization")?.replace(/^Bearer /, ""), env.API_KEY))
        return json({ error: "Your session expired. Refresh your courses, then try again." }, 401);
      const origin2 = request.headers.get("Origin");
      if (origin2 && origin2 !== DASHBOARD_ORIGIN) return json({ error: "Origin not allowed." }, 403);
      const result = await interpretQuestion(request, env);
      return json(result.body, result.status, { "Cache-Control": "no-store" });
    }
    if (request.method === "GET" && url.pathname === "/") {
      return json({
        ok: true,
        service: "TeachAssist marks Worker",
        endpoint: `${url.origin}/api/marks`,
        hint: "Sign in from the dashboard; it POSTs your credentials here."
      });
    }
    if (request.method === "GET" && /^\/api\/marks\/+$/i.test(url.pathname)) {
      return Response.redirect(`${url.origin}/api/marks${url.search}`, 308);
    }
    if (request.method === "GET" && /^\/api\/marks\/api\/marks\/?$/i.test(url.pathname)) {
      return json(
        {
          error: "The endpoint was added twice.",
          hint: "Use your Worker base URL; the app appends the /api/marks endpoint itself."
        },
        400
      );
    }
    if (request.method === "GET" && url.pathname === "/api/cached") {
      if (REQUIRE_API_KEY) {
        const provided = request.headers.get(API_KEY_HEADER) || url.searchParams.get("key");
        if (!env.API_KEY || !provided || !timingSafeEqual(provided, env.API_KEY)) {
          return json({ error: "Unauthorized" }, 401);
        }
      }
      if (!env.MARKS) return json({ error: "Cache is not configured (no KV binding)." }, 503);
      const raw = await env.MARKS.get("latest");
      if (!raw) {
        return json(
          { error: "No cached marks yet.", hint: "Sign in once, or wait for the daily sync." },
          404
        );
      }
      return new Response(raw, {
        status: 200,
        headers: { "content-type": "application/json; charset=utf-8", ...corsHeaders() }
      });
    }
    if (url.pathname !== "/api/marks" || request.method !== "GET" && request.method !== "POST") {
      return json({ error: "Not found", hint: "Use GET or POST /api/marks" }, 404);
    }
    const publicSignIn = request.method === "POST" && !url.searchParams.has("debug");
    const origin = request.headers.get("Origin");
    if (origin && origin !== DASHBOARD_ORIGIN) return json({ error: "Origin not allowed." }, 403);
    if (!publicSignIn && REQUIRE_API_KEY) {
      const provided = request.headers.get(API_KEY_HEADER) || url.searchParams.get("key");
      if (!env.API_KEY || !provided || !timingSafeEqual(provided, env.API_KEY)) {
        return json({ error: "Unauthorized" }, 401);
      }
    }
    let creds = null;
    if (request.method === "POST") {
      try {
        const reader = request.body?.getReader();
        if (!reader) throw new Error();
        let size = 0, chunks = [];
        for (; ; ) {
          const { done, value } = await reader.read();
          if (done) break;
          size += value.byteLength;
          if (size > 8192) {
            await reader.cancel();
            return json({ error: "Sign-in request is too large." }, 413);
          }
          chunks.push(value);
        }
        const bytes = new Uint8Array(size);
        let offset = 0;
        for (const chunk of chunks) {
          bytes.set(chunk, offset);
          offset += chunk.length;
        }
        const b = JSON.parse(new TextDecoder().decode(bytes));
        if (typeof b?.username !== "string" || !/^\d{1,20}$/.test(b.username.trim()) || typeof b.password !== "string" || !b.password || b.password.length > 1024) throw new Error();
        creds = { username: b.username.trim(), password: b.password };
      } catch {
        return json({ error: "Enter your student number and password." }, 400);
      }
    } else if (!env.TA_USERNAME || !env.TA_PASSWORD) {
      return json({ error: "Owner credentials are not configured." }, 400);
    }
    const debug = url.searchParams.get("debug");
    try {
      if (debug === "login") {
        const res = await loginResponse(env, creds);
        const jar = extractCookies(res);
        const location = res.headers.get("location") || "";
        return json({
          status: res.status,
          location,
          setCookieNames: Object.keys(jar),
          sessionCookieName: SESSION_COOKIE_NAME,
          hasSessionCookie: !!jar[SESSION_COOKIE_NAME],
          studentId: (location.match(/student_id=(\d+)/) || [])[1] || null,
          note: "No credentials or cookie values are included in this output."
        });
      }
      if (debug === "courses" || debug === "report") {
        const session2 = await login(env, creds);
        const listUrl = `${COURSE_LIST_URL}?student_id=${encodeURIComponent(session2.studentId)}`;
        const listHtml = session2.listHtml ?? await fetchWithSession(listUrl, session2, LOGIN_URL);
        if (debug === "courses") return text(listHtml);
        assertLoggedIn2(listHtml);
        const courses = await parseCourseList(listHtml);
        for (const c of courses) c.studentId = c.studentId || session2.studentId;
        let sid = url.searchParams.get("subject_id");
        const code = url.searchParams.get("code");
        if (!sid && code) {
          const match = courses.find(
            (c) => c.subjectId && (c.code || "").toUpperCase().includes(code.toUpperCase())
          );
          if (match) sid = match.subjectId;
        }
        if (!sid) {
          return json(
            {
              error: "Add &code=SNC (or your course code) or &subject_id=NNN.",
              courses: courses.map((c) => ({ code: c.code, subjectId: c.subjectId }))
            },
            400
          );
        }
        const html = await fetchWithSession(
          `${REPORT_URL_BASE}?subject_id=${encodeURIComponent(sid)}&student_id=${encodeURIComponent(session2.studentId)}`,
          session2,
          listUrl
        );
        return text(html);
      }
      const out = await scrapeMarks(env, creds);
      if (request.method === "GET") storeMarks(env, ctx, out);
      const session = publicSignIn ? await issueSession(env.API_KEY) : "";
      return json(out, 200, session ? { "X-TeachAssist-Session": session } : {});
    } catch (err) {
      if (err instanceof TeachAssistError) {
        return json({ error: err.message, code: err.code }, err.status);
      }
      return json({ error: "TeachAssist could not load your marks. Please try again.", code: "TA_REQUEST_FAILED" }, 502);
    }
  },
  /**
   * Cron Trigger (see [triggers] crons in wrangler.toml). Runs on a schedule,
   * logs into TeachAssist with the Worker secrets, scrapes the marks, and caches
   * them in KV so the dashboard loads instantly and stays current even when
   * nobody opens it. No request/response — failures are logged, not thrown.
   *
   * @param {ScheduledController} event
   * @param {{ TA_USERNAME?: string, TA_PASSWORD?: string, MARKS?: KVNamespace }} env
   * @param {{ waitUntil: (p: Promise<any>) => void }} ctx
   */
  async scheduled(event, env, ctx) {
    ctx.waitUntil(runDailySync(env));
  }
};
async function scrapeMarks(env, creds) {
  const session = await login(env, creds);
  const listUrl = `${COURSE_LIST_URL}?student_id=${encodeURIComponent(session.studentId)}`;
  const listHtml = session.listHtml ?? await fetchWithSession(listUrl, session, LOGIN_URL);
  assertLoggedIn2(listHtml);
  const courses = await parseCourseList(listHtml);
  for (const c of courses) c.studentId = c.studentId || session.studentId;
  if (DEBUG) console.log(`Parsed ${courses.length} courses`);
  if (FETCH_REPORTS) {
    await Promise.all(
      courses.map(async (c) => {
        if (!c.subjectId || !c.studentId) {
          c.evaluations = [];
          return;
        }
        try {
          const reportUrl = `${REPORT_URL_BASE}?subject_id=${encodeURIComponent(c.subjectId)}&student_id=${encodeURIComponent(c.studentId)}`;
          const reportHtml = await fetchWithSession(reportUrl, session, COURSE_LIST_URL);
          c.evaluations = await parseEvaluations(reportHtml);
          const cm = parseReportCourseMark(reportHtml);
          if (cm != null && c.currentMark == null) c.currentMark = cm;
        } catch (err) {
          c.evaluations = [];
          c.reportError = safeMessage(err);
        }
      })
    );
  } else {
    for (const c of courses) c.evaluations = [];
  }
  return courses.map((c) => ({
    code: c.code,
    name: c.name,
    currentMark: c.currentMark,
    midterm: c.midterm ?? null,
    evaluations: c.evaluations,
    ...c.reportError ? { reportError: c.reportError } : {}
  }));
}
function storeMarks(env, ctx, out) {
  if (!env || !env.MARKS || !Array.isArray(out)) return;
  const scrapedAt = (/* @__PURE__ */ new Date()).toISOString();
  const day = scrapedAt.slice(0, 10);
  const writes = Promise.all([
    env.MARKS.put("latest", JSON.stringify({ scrapedAt, courses: out })),
    env.MARKS.put(
      `snapshot:${day}`,
      JSON.stringify({ date: scrapedAt, overall: overallOf(out), marks: marksOf(out) }),
      { expirationTtl: 60 * 60 * 24 * 400 }
      // keep ~13 months of daily history
    )
  ]).catch((e) => {
    if (DEBUG) console.log("KV write failed:", safeMessage(e));
  });
  if (ctx && typeof ctx.waitUntil === "function") ctx.waitUntil(writes);
  return writes;
}
async function runDailySync(env) {
  if (!env || !env.MARKS) {
    if (DEBUG) console.log("Daily sync skipped: no KV (MARKS) binding.");
    return;
  }
  if (!env.TA_USERNAME || !env.TA_PASSWORD) {
    console.log("Daily sync skipped: TA_USERNAME / TA_PASSWORD secrets are not set.");
    return;
  }
  try {
    const out = await scrapeMarks(env, null);
    await storeMarks(env, null, out);
    console.log(`Daily sync OK: cached ${out.length} courses.`);
  } catch (err) {
    console.log("Daily sync failed:", safeMessage(err));
  }
}
function displayMarkOf(c) {
  if (c && typeof c.currentMark === "number") return c.currentMark;
  if (c && typeof c.midterm === "number") return c.midterm;
  return null;
}
function overallOf(courses) {
  const m = (courses || []).map(displayMarkOf).filter((x) => x != null);
  return m.length ? Math.round(m.reduce((a, b) => a + b, 0) / m.length * 10) / 10 : null;
}
function marksOf(courses) {
  return Object.fromEntries((courses || []).map((c) => [c.code, displayMarkOf(c)]));
}
async function parseCourseList(html) {
  const courses = [];
  const seen = /* @__PURE__ */ new Set();
  let row = null;
  const rewriter = new HTMLRewriter().on("tr", {
    element(el) {
      const current = { textBuf: "", subjectId: null, studentId: null };
      row = current;
      el.onEndTag(() => {
        finalizeCourseRow(current, courses, seen);
        if (row === current) row = null;
      });
    }
  }).on('a[href*="viewReport"]', {
    element(el) {
      if (!row) return;
      const href = el.getAttribute("href") || "";
      const sub = href.match(/subject_id=(\d+)/);
      const stu = href.match(/student_id=(\d+)/);
      if (sub) row.subjectId = sub[1];
      if (stu) row.studentId = stu[1];
    }
  }).on("*", {
    text(t) {
      if (row) row.textBuf += t.text;
    }
  });
  await rewriter.transform(new Response(html)).arrayBuffer();
  return courses;
}
function finalizeCourseRow(rowState, out, seen) {
  const text2 = collapseWhitespace(rowState.textBuf);
  if (!text2) return;
  const code = extractCourseCode(text2);
  const currentMark = extractCurrentMark(text2);
  const midterm = extractMidterm(text2);
  if (!rowState.subjectId && !code) return;
  let name = text2.replace(/current mark\s*=\s*[\d.]+\s*%/i, "").replace(/midterm mark\s*:?\s*[\d.]+\s*%/i, "").trim();
  name = collapseWhitespace(name).slice(0, 200);
  if (!name) name = code || "Unknown course";
  const key2 = rowState.subjectId || code;
  if (seen.has(key2)) return;
  seen.add(key2);
  out.push({
    code,
    name,
    currentMark,
    midterm,
    subjectId: rowState.subjectId,
    studentId: rowState.studentId
  });
}
function extractCourseCode(text2) {
  const m = text2.match(COURSE_CODE_RE);
  return m ? m[1] : null;
}
function extractCurrentMark(text2) {
  const m = text2.match(/current mark\s*=\s*([\d.]+)\s*%/i);
  return m ? parseFloat(m[1]) : null;
}
function extractMidterm(text2) {
  const m = text2.match(/midterm\s*mark\s*:?\s*([\d.]+)\s*%/i);
  return m ? parseFloat(m[1]) : null;
}
function parseReportCourseMark(html) {
  const m = html.match(
    /([\d.]+)\s*%\s*<\/div>\s*<\/td>\s*<td>\s*<div[^>]*>\s*Course\s*<\/div>/i
  );
  return m ? parseFloat(m[1]) : null;
}
async function parseEvaluations(html) {
  const evaluations = [];
  let row = null;
  const rewriter = new HTMLRewriter().on("tr", {
    element(el) {
      const colour = cellColour(el);
      const current = { category: colour ? STRAND_COLOURS[colour] : null, buf: "" };
      row = current;
      el.onEndTag(() => {
        flushCategoryRow(current, evaluations);
        if (row === current) row = null;
      });
    }
  }).on("*", {
    text(t) {
      if (row) row.buf += t.text;
    }
  });
  await rewriter.transform(new Response(html)).arrayBuffer();
  return evaluations;
}
function cellColour(el) {
  const bg = el.getAttribute("bgcolor");
  if (bg) return normaliseHex(bg);
  const style = el.getAttribute("style");
  if (style) {
    const m = style.match(/background(?:-color)?\s*:\s*#?([0-9a-fA-F]{6})/);
    if (m) return m[1].toLowerCase();
  }
  return null;
}
function normaliseHex(value) {
  const m = String(value).trim().replace(/^#/, "").match(/^[0-9a-fA-F]{6}$/);
  return m ? value.trim().replace(/^#/, "").toLowerCase() : null;
}
function flushCategoryRow(rowState, out) {
  if (!rowState.category) return;
  const text2 = collapseWhitespace(rowState.buf);
  const pcts = [...text2.matchAll(/([\d.]+)\s*%/g)].map((m) => parseFloat(m[1]));
  if (!pcts.length) return;
  const name = (text2.split(/[\d.]+\s*%/)[0] || "").trim() || rowState.category;
  out.push({
    name,
    category: rowState.category,
    percent: pcts[pcts.length - 1],
    weight: pcts.length > 1 ? pcts[0] : null
  });
}
function decodeEntities(s) {
  return s.replace(/&nbsp;/gi, " ").replace(/&amp;/gi, "&").replace(/&lt;/gi, "<").replace(/&gt;/gi, ">").replace(/&quot;/gi, '"').replace(/&apos;|&#0*39;/gi, "'").replace(/&#x([0-9a-f]+);/gi, (_, h) => codePoint(parseInt(h, 16))).replace(/&#(\d+);/g, (_, d) => codePoint(parseInt(d, 10)));
}
function codePoint(n) {
  try {
    return Number.isFinite(n) && n > 0 && n <= 1114111 ? String.fromCodePoint(n) : "";
  } catch {
    return "";
  }
}
function collapseWhitespace(s) {
  return decodeEntities(s).replace(/\s+/g, " ").trim();
}
function corsHeaders() {
  return {
    "Access-Control-Allow-Origin": DASHBOARD_ORIGIN,
    "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
    "Access-Control-Allow-Headers": `Content-Type, Authorization, ${API_KEY_HEADER}`,
    "Access-Control-Expose-Headers": "X-TeachAssist-Session",
    "Cache-Control": "no-store",
    "Access-Control-Max-Age": "86400",
    Vary: "Origin"
  };
}
function json(data, status = 200, extraHeaders = {}) {
  return new Response(JSON.stringify(data, null, 2), {
    status,
    headers: {
      "content-type": "application/json; charset=utf-8",
      ...corsHeaders(),
      ...extraHeaders
    }
  });
}
function text(body, status = 200) {
  return new Response(body, {
    status,
    headers: { "content-type": "text/plain; charset=utf-8", ...corsHeaders() }
  });
}
function safeMessage(err) {
  let msg = err && err.message || String(err) || "Unknown error";
  msg = msg.replace(/password=[^&\s]*/gi, "password=***");
  return msg;
}
function timingSafeEqual(a, b) {
  if (typeof a !== "string" || typeof b !== "string") return false;
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

// worker/src/pages.js
function json2(body, status = 200) {
  return Response.json(body, { status, headers: { "Cache-Control": "no-store" } });
}
var pages_default = {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    if (!url.pathname.startsWith("/api/")) return env.ASSETS.fetch(request);
    const origin = request.headers.get("Origin");
    if (origin && origin !== url.origin) return json2({ error: "Origin not allowed." }, 403);
    if (url.pathname === "/api/status" && request.method === "GET") {
      return json2({ service: "TeachAssist", studentSignIn: true, version: 1 });
    }
    if (!["/api/marks", "/api/assistant"].includes(url.pathname) || url.search) {
      return json2({ error: "Not found." }, 404);
    }
    if (request.method !== "POST") return json2({ error: "Use POST." }, 405);
    if (url.pathname === "/api/assistant" && (!env.AI || !env.API_KEY)) {
      return json2({ error: "AI is not configured on this site yet. The quick calculator still works." }, 503);
    }
    const headers = new Headers(request.headers);
    headers.delete("Origin");
    headers.delete("x-api-key");
    const internalRequest = new Request(request, { headers });
    const response = await index_default.fetch(internalRequest, {
      AI: env.AI,
      API_KEY: env.API_KEY
      // Deliberately omit owner credentials and the shared MARKS cache.
    }, ctx);
    const result = new Response(response.body, response);
    for (const name of [...result.headers.keys()]) {
      if (name.startsWith("access-control-")) result.headers.delete(name);
    }
    result.headers.set("Cache-Control", "no-store");
    return result;
  }
};
export {
  pages_default as default
};
